builders:
  paddinger_generator:
    import: "package:paddinger/paddinger.dart"
    builder_factories: ["paddingerGenerator"]
    build_extensions: {".dart": [".paddinger.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]