name: paddinger_packages

repository: https://github.com/dklenowski/paddinger.git

packages:
  - packages/**

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

    environment:
      sdk: '>=3.2.6 <4.0.0'
      flutter: ">=1.17.0"
    dependencies:
    dev_dependencies:
      flutter_lints: ^3.0.1
