name: paddinger_annotations
description: >
  Annotations for the paddinger Flutter code-generator.
  This package does nothing without paddinger too.
version: 3.2.0
repository: https://github.com/dklenowski/paddinger
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1


flutter:
